### ISSUE TITLE
PSoC6 CY8CKIT-062-WIFI-BT "fatal error: cy_ml_inference.h: No such file or directory"

### ISSUE THREAD

**Issue by surya-psoc6** [Infineon/mtb-example-ml-profiler#1]
**Prerequisites**

Can you reproduce the problem reliably? yes

Did you check current release notes for known issues? No

If this is not the latest release, have you checked newer releases? 

**Description**:

**Steps to Reproduce:**

1. install 
"mtb-example-ml-profiler"

2.  error : source/nn.h:49:10: fatal error: cy_ml_inference.h: No such file or directory

3. Occurs during building

**Expected Result:**

0 errors

**Actual Result:**

fatal error: cy_ml_inference.h: No such file or directory

**Frequency (1/1, 1/50, 1/100):**

**Build/Commit:** 

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**
CY8CKIT-062-WIFI-BT
The chip or kit you are working with

**Host OS and Version:**

Windows

**Compiler:**
ModusToolbox 2.3.0
tools_2.3
Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by rmbk19** [comment]
Hi @surya-psoc6, 

I believe this query is answered in the thread -  [TinyML on PSOC6?](https://community.cypress.com/t5/PSoC-6-MCU/TinyML-on-PSOC6/m-p/270526#M9546) 

Adding the response here for reference - 
To use our Machine Learning solution, you need to install the ModusToolbo 2.2.3 patch. This patch is not publicly available. You need to contact our team to get early access.
http://go.cypress.com/modustoolbox-ml
Please fill-up the form above and someone will contact you.

Regards, 
Rakshith
