### ISSUE TITLE
Dr. Surya

### ISSUE THREAD

**Issue by surya-psoc6** [Infineon/mtb-example-ml-profiler#2]
**Prerequisites**

Can you reproduce the problem reliably? Yes.

Did you check current release notes for known issues? Yes

If this is not the latest release, have you checked newer releases? 

**Description**:

I was able to sort out the issue, and the program is loaded perfectly on PSoC6 now.

But I've been facing an issue with the ML Configurator tool. I'm unable to open it like Library Manager to give validation commands.
Please advise.

**Steps to Reproduce:**

1. Load the ML-profiler example code on PSoC6 with ModustoolBox

2. Run the ML configurator 1.10 in quick launch or .exe from the tools_2.3

3. We can not see the pop-up of window like Device configurator or Library manager.

**Expected Result:**

A pop-up window with commands in ML configurator 1.10

**Actual Result:**

I can't see a window to apply commands.

**Frequency (1/1, 1/50, 1/100):**

**Build/Commit:**

Please specify the release, like 1.4.1. If there is no release, give us the commit for the code you used.

**Target:**

The chip or kit you are working with

**Host OS and Version:**
Windows

MacOS, Windows, Linux

**Compiler:**
Modustoolbox 2.3.0 with patch 2.3.1.4663

Include the version!

**Environment**

Provide the context surrounding this problem. Perhaps an IDE, a debug probe, an RTOS, etc. (and versions)

**Comment by rmbk19** [comment]
Hi @surya-psoc6, 

Can you please open Task Manager and check if ML Configurator shows up in Task Manager as shown? - 
![image](https://user-images.githubusercontent.com/57936462/120289198-aadbec80-c2de-11eb-96c8-c5305c1004a1.png)

Regards, 
Rakshith

**Comment by surya-psoc6** [comment]
Hi Rakshith,

Yes, I can see both of them in the task bar.


Regards,
Sandeep Surya


________________________________

**Comment by surya-psoc6** [comment]
I can't see the following though!

[cid:c263fe9d-3418-4a05-b08b-f681a24970f4]


Regards,
Sandeep Surya


________________________________

**Comment by rmbk19** [comment]
Hi @surya-psoc6, 

I am not sure what was attached in your previous comment. 
The ML Configurator sometimes could be hidden. Can you please try using the Alt+Space+M shortcut followed by the arrow keys to move the window and let me know if that works? Please ensure that ML Configurator is selected and is in focus before trying this.

Regards, 
Rakshith

**Comment by surya-psoc6** [comment]
Hi Rakshith,

The issue was due to the anti-virus installed.
Anyhow, I can access the ML configurator now.
Do you know how to read the "small_mlp_mnist.h5" in the pretrained_models folder?
How can I edit a model or where can I download other models to test?

Regards,
Sandeep

**Comment by rmbk19** [comment]
Hi Sandeep, 

Can you please let me know the reason why ML Configurator was blocked by your anti-virus and also can you please let me know which anti-virus you are using?

The ML Configurator currently does not support modifying or training a model. You will have to train the model externally. Please refer to these links for further information regarding this - 
https://keras.io/getting_started/intro_to_keras_for_engineers/
https://www.tensorflow.org/guide/keras/save_and_serialize

Regards, 
Rakshith

**Comment by surya-psoc6** [comment]
Hi,

No, I couldn't find the reason. I use bit defender, and I had a doubt that it might be blocking these .exe files. After deactivating it for some time, I could see the pop-up windows.
It was also blocking some of the other .exe files of MTB.

Regards,
Sandeep Surya



________________________________

**Comment by rmbk19** [comment]
Hi Sandeep, 

Anti-virus should generally not be flagging ModusToolbox or its configurators. I will create an internal ticket so that our development team can check the reason why the tool was blocked. Thank you very much for pointing this out!

Regards, 
Rakshith
